#!/bin/bash

declare -A SUPPORTED_MACHINE=([cl-som-imx8]=1 [ucm-imx8m-mini]=1)

get_meta() {
if [[ -d ${dir} ]];then
git -C ${dir} remote update
git -C ${dir} pull
else
git clone ${url} ${branch} ${dir}
fi
}

get_meta_compulab() {
dir="../sources/meta-compulab"
branch="-b devel"
url="https://github.com/compulab-yokneam/meta-compulab"
get_meta ${url} ${branch} ${dir}
}

get_meta_compulab_bsp() {
dir="../sources/meta-compulab-bsp"
branch="-b master"
url="https://github.com/compulab-yokneam/meta-compulab-bsp"
get_meta ${url} ${branch} ${dir}
}

get_meta_bsp_imx8mm() {
dir="../sources/meta-bsp-imx8mm"
branch="-b devel"
url="https://github.com/compulab-yokneam/meta-bsp-imx8mm"
get_meta ${url} ${branch} ${dir}
}

get_meta_bsp_imx8mq() {
dir="../sources/meta-bsp-imx8mq"
branch="-b devel-next"
url="https://github.com/compulab-yokneam/meta-bsp-imx8mq"
get_meta ${url} ${branch} ${dir}
}

mod_bblayer() {
# Get CompuLab Main meta layer
get_meta_compulab
get_meta_compulab_bsp
get_meta_bsp_imx8mq
get_meta_bsp_imx8mm
# A mandatory bsp layer: kernel, u-boot, imx-boot
awk '!/^#/' ${TEMPL}/bblayers.conf.append | tee -a ${BBLAYERS_CONF} > /dev/null
}

mod_local() {
echo << eof
layer.conf contains all definitions
eof
}

CWD=$(pwd)
PROGNAME=${BASH_SOURCE[0]}
[ $(basename -- $BASH_SOURCE) == $(basename -- $0) ] && EXIT="exit" || EXIT="return"

if [[ $(id -u) -eq 0 ]]; then
    echo "ERROR: do not use the BSP as root. Exiting..."
    ${EXIT}
fi

BBLAYERS_CONF=conf/bblayers.conf
BB_CL_CONF_DONE=conf/bb_cl_conf.done
LOCAL_CONF=conf/local.conf

if ([ ! -f ${BBLAYERS_CONF} ] || [ ! -f ${LOCAL_CONF} ]);then
cat << eom
    Warning: Files ${BBLAYERS_CONF} and ${LOCAL_CONF} not found.
    Make sure that the scritp issued at a correct location.
eom
    ${EXIT} 2
fi

[[ -n ${FORCE} ]] && rm -rf ${BB_CL_CONF_DONE}

if [ -f ${BB_CL_CONF_DONE} ];then
cat << eom
    Note: Already issued.
    Nothing to be done.
eom
    ${EXIT} 0
fi

eval $(awk '(/MACHINE|DISTRO/)&&(gsub(/'"'"'/,"")&&($0=$1"="$NF))' ORS=";" ${LOCAL_CONF})

if [[ ${SUPPORTED_MACHINE[${MACHINE}]} -ne 1 ]];then
cat << eom
    ${MACHINE} is not in supported machine list.
    Error exit.
eom
    ${EXIT} 0
fi

cat << eom
    Prepare: ${MACHINE}:${DISTRO} ...
eom

mod_bblayer
mod_local

cat << eom
    Note: Files ${BBLAYERS_CONF} and ${LOCAL_CONF} updated successfully.
eom

cat << eom > ${BB_CL_CONF_DONE}
$(date)
eom

unset IMAGE_FEATURES CORE_IMAGE_EXTRA_INSTALL
${EXIT} 0
