#!/bin/bash -e

MACHINE=${MACHINE:-cl-som-imx7}
DISTRO=${DISTRO:-fsl-imx-x11}
EULA=1
T="../sources/meta-mender-compulab/imx7/templates"

[[ -f fsl-setup-release.sh ]] && source fsl-setup-release.sh $@ || true

for _d in ${T}/*;do
	_file=$(basename ${_d})
	for _f in ${_d}/*;do
		[[ -f ${_f} ]] || continue
		cat ${_f} >> conf/${_file}
	done;
done
