#!/bin/bash

dst=mmcblk2
DST=${DST:-/dev/${dst}}
dst=$(basename ${DST})

# File system
export QUIET=Yes
export DST=${DST}
cl-deploy

# Bootloader
declare -A bootcan=( [mmcblk1]=mmcblk1 [mmcblk2]=mmcblk2boot0 )
export IMX_BOOT=$(ls /boot/*flash_evk | tail -1)
export IMX_DEV=/dev/${bootcan[${dst}]}
cl-uboot
