#!/bin/bash -e
MACHINE=${MACHINE:-ucm-imx8m-mini}
_MACHINE=${MACHINE}
DISTRO=${DISTRO:-fslc-framebuffer}
EULA=1

FSLC_SETUP=$(pwd)/sources/compulab-fslc-bsp/tools/setup-env
D=$(dirname $(readlink -f ${BASH_SOURCE[0]}))

source setup-environment $@

NO_SETUP=1 source ${FSLC_SETUP}
source ${D}/setup-conf

export MACHINE=${_MACHINE}

git -C  ${BUILDDIR}/../sources/meta-mender revert --no-edit d1e1c04e53a9fc572beab10ded3681a864863c20
